### ISSUE TITLE
请问怎么配置域名

### ISSUE THREAD

**Issue by jlcool** [chenxianqi/kefu_server#1]
请问怎么配置域名，外网访问？

**Comment by chenxianqi** [comment]
直接在con/app.conf下面配置httpaddr = "localhost"
也可以使用nginx代理,集体配置请看beego官网

**Comment by jlcool** [comment]
不好意思，不会go语言，试了配置httpaddr，为空所有域名可以访问，但是是指定端口，指定域名就闪退。windows服务器

**Comment by chenxianqi** [comment]
有错误日志吗？看一下项目根目录的日志文件

**Comment by jlcool** [comment]
当前环境为测试环境2020/03/07 22:55:13.271 [I] [asm_amd64.s:1357]  http server Running on http://域名:8080
2020/03/07 22:55:13.272 [C] [asm_amd64.s:1357]  ListenAndServe:  listen tcp 服务器IP:8080: bind: The requested address is not valid in its context.
域名和ip已替换

**Comment by chenxianqi** [comment]
那你配置端口或者域名是否正常？，这个看起来貌似是你访问了某个接口导致报上下文错误

**Comment by jlcool** [comment]
你好，都是正常的，ip是服务器外网ip

**Comment by chenxianqi** [comment]
你直接配置外网IP或者localhost可以跑起来么？
