### ISSUE TITLE
信息存储问题

### ISSUE THREAD

**Issue by cuijiaxu** [chenxianqi/kefu_server#2]
您好， 
        能否咨询下，server端如何获取到的全量信息。
       从代码看，人工客服模式的时候，客服的前端直接把消息发给mimc了，并没有给后端啊。

谢谢

**Comment by chenxianqi** [comment]
目前是机器人中转入库的

**Comment by chenxianqi** [comment]
develop 分支已经把这块改掉了，直接api push

**Comment by cuijiaxu** [comment]
好的。明白了
